name: UEFI
# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build-uefi:
    name: UEFI
    runs-on: ubuntu-latest
    steps:
      - 
       name: Checkout
       uses: actions/checkout@v2
      - 
       name: Build
       run: | 
         docker build -t plutoboy -f build/UEFI/Dockerfile .
         docker run -v $(pwd):/mnt plutoboy
      -
       name: Package Build
       run: |
         zip -r plutoboy_uefi.zip bin/Plutoboy.efi
      - 
       name: Archive Build Output
       uses: actions/upload-artifact@v2
       with:
          name: plutoboy_uefi
          path: plutoboy_uefi.zip
