# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build-vita:
    name: PSVita
    runs-on: ubuntu-latest
    steps:
      - 
       name: Checkout
       uses: actions/checkout@v2
      - 
       name: Build
       run: | 
         docker build -t plutoboy -f build/Vita/Dockerfile .
         docker run -v $(pwd):/mnt plutoboy
      -
       name: Package Build
       run: |
         zip -r plutoboy_vita.zip Plutoboy.vpk
      - 
       name: Archive Build Output
       uses: actions/upload-artifact@v2
       with:
          name: plutoboy_vita
          path: plutoboy_vita.zip
