name: Android
# Run this workflow every time a new commit pushed to your repository
on: push
    schedule:
      - cron: '0 0 * * 0' # Once per week on Sunday 00:00

jobs:
  build-android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - 
       name: Checkout
       uses: actions/checkout@v2
      - 
       name: Build
       run: | 
         docker build -t plutoboy -f build/Android/Dockerfile .
         docker run -v $(pwd):/mnt plutoboy
      -
       name: Package Build
       run: |
         zip -r plutoboy_android_apk.zip Plutoboy.apk
      - 
       name: Archive Build Output
       uses: actions/upload-artifact@v2
       with:
          name: plutoboy_android_apk
          path: plutoboy_android_apk.zip
